OnlineMedic.Web/ViewModels/DoctorViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace OnlineMedic.Web.ViewModels
{
    public class DoctorViewModel
    {
        public string UserId { get; set; }

        [Required]
        [StringLength(50)]
        public string FullName { get; set; }

        [Required]
        public float ServicePrice { get; set; }

        [Required]
        public string Biography { get; set; }

        [Required]
        public double Latitude { get; set; }

        [Required]
        public double Longitude { get; set; }

        [Required]
        public int CategoryId { get; set; }
    }
}

OnlineMedic.Web/Controllers/CalendarController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.SignalR;
using OnlineMedic.Data.Models;
using OnlineMedic.Web.BusinessLogic;
using OnlineMedic.Web.Hubs;
using OnlineMedic.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineMedic.Web.Controllers
{
    public class CalendarController : Controller
    {
        private readonly ICalendarLogic _calendarLogic;
        private readonly IPatientLogic _patientLogic;

        public CalendarController(ICalendarLogic cl, IPatientLogic pl)
        {
            _calendarLogic = cl;
            _patientLogic = pl;
        }

        #region View Actions
        // GET: Calendar
        public ActionResult Doctor(string id, string date)
        {
            //Select start date
            DateTime startDate;
            if (string.IsNullOrEmpty(date))
            {
                startDate = DateTime.Now;
            }
            else
            {
                startDate = DateTime.Parse(date);

                startDate = new DateTime(startDate.Year, startDate.Month, startDate.Day, 1, 0, 0);
                var nowDateTemp = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, 1, 0, 0);
                if (startDate < nowDateTemp)
                {
                    startDate = DateTime.Now;
                }
            }
            startDate = new DateTime(startDate.Year, startDate.Month, startDate.Day, 1, 0, 0);

            //Generate days names
            List<string> daysNameHtmlList = new List<string>();
            for (int i = 0; i < 7; i++)
            {
                var tempDate = startDate.AddDays(i);
                string dayString = $"<th class='text-center'><div>{tempDate.ToShortDateString()}</div><div>{tempDate.DayOfWeek.ToString()}</div></th>";
                daysNameHtmlList.Add(dayString);
            }
            ViewBag.DaysNames = daysNameHtmlList;


            //Get entries form DB and create List with entries info
            var calendarEntriesDb = _calendarLogic.GetDoctorsCalendar(id, startDate);
            List<List<CalendarEntryViewModel>> calendarEntriesList = new List<List<CalendarEntryViewModel>>();
            for (int j = 0; j < 14; j++)
            {
                List<CalendarEntryViewModel> tempList = new List<CalendarEntryViewModel>();                
                for (int i = 0; i < 7; i++)
                {
                    var tempDate = startDate.AddDays(i);
                    var dateToCompare = new DateTime(tempDate.Year, tempDate.Month, tempDate.Day, 8 + j, 0, 0);
                    var calEntry = new CalendarEntryViewModel
                    {
                        Time = (8 + j).ToString(),
                        Status = "R",
                        Date = tempDate.ToShortDateString()
                    };

                    foreach (var entryFromDb in calendarEntriesDb)
                    {
                        if (dateToCompare.Ticks == entryFromDb.Date.Ticks)
                        {
                            if (entryFromDb.PatientId == User.Identity.GetUserId())
                            {
                                calEntry.Status = "M";
                                if (entryFromDb.Confirmed == false)
                                {
                                    calEntry.Status = "P";
                                }
                            }
                            else
                            {
                                calEntry.Status = "F";
                            }
                        }
                    }
                    tempList.Add(calEntry);
                }
                calendarEntriesList.Add(tempList);
            }

            ViewBag.CalendarEntries = calendarEntriesList;
            ViewBag.DoctorId = id;
            ViewBag.PatientId = User.Identity.GetUserId();

            var prevDate = startDate.AddDays(-7);
            prevDate = new DateTime(prevDate.Year, prevDate.Month, prevDate.Day, 1, 0, 0);
            var nowDate = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, 1, 0, 0);
            if (prevDate < nowDate)
            {
                prevDate = DateTime.Now;
            }
            var nextDate = startDate.AddDays(7);

            ViewBag.PrevDate = prevDate.ToShortDateString();
            ViewBag.NextDate = nextDate.ToShortDateString();

            return View();
        }

        public ActionResult MyCalendarDoctor(string date)
        {
            //Select start date
            DateTime startDate;
            if (string.IsNullOrEmpty(date))
            {
                startDate = DateTime.Now;
            }
            else
            {
                startDate = DateTime.Parse(date);

                startDate = new DateTime(startDate.Year, startDate.Month, startDate.Day, 1, 0, 0);
                var nowDateTemp = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, 1, 0, 0);
                if (startDate < nowDateTemp)
                {
                    startDate = DateTime.Now;
                }
            }
            startDate = new DateTime(startDate.Year, startDate.Month, startDate.Day, 1, 0, 0);

            //Generate days names
            List<string> daysNameHtmlList = new List<string>();
            for (int i = 0; i < 7; i++)
            {
                var tempDate = startDate.AddDays(i);
                string dayString = $"<th class='text-center'><div>{tempDate.ToShortDateString()}</div><div>{tempDate.DayOfWeek.ToString()}</div></th>";
                daysNameHtmlList.Add(dayString);
            }
            ViewBag.DaysNames = daysNameHtmlList;


            //Get entries form DB and create List with entries info
            var calendarEntriesDb = _calendarLogic.GetDoctorsCalendar(User.Identity.GetUserId(), startDate);
            List<List<CalendarEntryViewModel>> calendarEntriesList = new List<List<CalendarEntryViewModel>>();
            for (int j = 0; j < 14; j++)
            {
                List<CalendarEntryViewModel> tempList = new List<CalendarEntryViewModel>();
                for (int i = 0; i < 7; i++)
                {
                    var tempDate = startDate.AddDays(i);
                    var dateToCompare = new DateTime(tempDate.Year, tempDate.Month, tempDate.Day, 8 + j, 0, 0);
                    var calEntry = new CalendarEntryViewModel
                    {
                        Time = (8 + j).ToString(),
                        Status = "E",
                        Date = tempDate.ToShortDateString()
                    };

                    foreach (var entryFromDb in calendarEntriesDb)
                    {
                        if (dateToCompare.Ticks == entryFromDb.Date.Ticks)
                        {
                            if (entryFromDb.Free == true)
                            {
                                calEntry.Status = "F";
                            }
                            else
                            {
                                calEntry.Status = "R";
                                calEntry.Name = entryFromDb.Patient.FullName;
                                calEntry.UserId = entryFromDb.PatientId;
                                if (entryFromDb.Confirmed == false)
                                {
                                    calEntry.Status = "P";
                                }
                            }
                        }
                    }
                    tempList.Add(calEntry);
                }
                calendarEntriesList.Add(tempList);
            }

            ViewBag.CalendarEntries = calendarEntriesList;
            ViewBag.DoctorId = User.Identity.GetUserId();

            var prevDate = startDate.AddDays(-7);
            prevDate = new DateTime(prevDate.Year, prevDate.Month, prevDate.Day, 1, 0, 0);
            var nowDate = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, 1, 0, 0);
            if (prevDate < nowDate)
            {
                prevDate = DateTime.Now;
            }
            var nextDate = startDate.AddDays(7);

            ViewBag.PrevDate = prevDate.ToShortDateString();
            ViewBag.NextDate = nextDate.ToShortDateString();

            return View();
        }

        public ActionResult MyCalendarPatient(string date)
        {
            //Select start date
            DateTime startDate;
            if (string.IsNullOrEmpty(date))
            {
                startDate = DateTime.Now;
            }
            else
            {
                startDate = DateTime.Parse(date);

                startDate = new DateTime(startDate.Year, startDate.Month, startDate.Day, 1, 0, 0);
                var nowDateTemp = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, 1, 0, 0);
                if (startDate < nowDateTemp)
                {
                    startDate = DateTime.Now;
                }
            }
            startDate = new DateTime(startDate.Year, startDate.Month, startDate.Day, 1, 0, 0);

            //Generate days names
            List<string> daysNameHtmlList = new List<string>();
            for (int i = 0; i < 7; i++)
            {
                var tempDate = startDate.AddDays(i);
                string dayString = $"<th class='text-center'><div>{tempDate.ToShortDateString()}</div><div>{tempDate.DayOfWeek.ToString()}</div></th>";
                daysNameHtmlList.Add(dayString);
            }
            ViewBag.DaysNames = daysNameHtmlList;


            //Get entries form DB and create List with entries info
            var calendarEntriesDb = _calendarLogic.GetPatientsCalendar(User.Identity.GetUserId(), startDate);
            List<List<CalendarEntryViewModel>> calendarEntriesList = new List<List<CalendarEntryViewModel>>();
            for (int j = 0; j < 14; j++)
            {

OnlineMedic.Web/Controllers/PatientsController.cs
using Microsoft.AspNet.Identity;
using OnlineMedic.Data.DataTransport;
using OnlineMedic.Data.Models;
using OnlineMedic.Web.BusinessLogic;
using OnlineMedic.Web.Filters;
using OnlineMedic.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineMedic.Web.Controllers
{
    [Authorize]
    public class PatientsController : Controller
    {
        private readonly IPatientLogic _patientLogic;
        private readonly IMedicalExaminationLogic _medicalExaminationLogic;

        public PatientsController(IPatientLogic patientLogic, IMedicalExaminationLogic medicalLogic)
        {
            _patientLogic = patientLogic;
            _medicalExaminationLogic = medicalLogic;
        }
        // GET: Patients

        [RolesAuthorizationFilter(Roles = "Doctor")]
        public ActionResult Index()
        {
            var patients = _patientLogic.GetAll();
            var patientsViewModel = AutoMapper.Mapper.Map<IEnumerable<Patient>, IEnumerable<PatientListViewModel>>(patients);

            return View(patientsViewModel);
        }

        [RolesAuthorizationFilter(Roles = "Doctor")]
        public ActionResult AllRecords(string patientId)
        {
            var records = _medicalExaminationLogic.GetAllRecordsFromPatientShort(patientId);
            var recordsViewModel = AutoMapper.Mapper.Map<IEnumerable<RecordShort>, IEnumerable<RecordListViewModel>>(records);
            return View(recordsViewModel);
        }

        [RolesAuthorizationFilter(Roles = "Doctor")]
        public ActionResult Records(string patientId, int recordId)
        {
            var record = _medicalExaminationLogic.GetRecord(recordId);
            var recordViewModel = AutoMapper.Mapper.Map<Record, RecordViewModel>(record);
            return View(recordViewModel);
        }

        [RolesAuthorizationFilter(Roles = "Doctor")]
        public ActionResult AddRecord(string patientId)
        {
            return View();
        }

        [RolesAuthorizationFilter(Roles = "Doctor")]
        [HttpPost]
        public ActionResult AddRecord(string patientId, RecordCreateViewModel record)
        {
            if (ModelState.IsValid)
            {
                var recordData = new Record
                {
                    Date = DateTime.Now,
                    Title = record.Title,
                    Text = record.Text,
                    DoctorId = User.Identity.GetUserId(),
                    PatientId = patientId
                };
                _medicalExaminationLogic.AddRecord(recordData);
                _medicalExaminationLogic.SaveChanges();

                string folderPath = Server.MapPath("~/Documents/" + recordData.Id);
                if (Directory.Exists(folderPath) == false)
                {
                    Directory.CreateDirectory(folderPath);
                }
                foreach (string upload in Request.Files)
                {
                    if (Request.Files[upload].ContentLength == 0) continue;
                    string pathToSave = Server.MapPath("~/Documents/" + recordData.Id);
                    string filename = Path.GetFileName(Request.Files[upload].FileName);
                    Request.Files[upload].SaveAs(Path.Combine(pathToSave, filename));

                    var recordFile = new RecordFile { RecordId = recordData.Id, FileLocation = Path.Combine(pathToSave, filename) };
                    _medicalExaminationLogic.AddRecordFile(recordFile);
                }
                _medicalExaminationLogic.SaveChanges();

                return RedirectToAction("AllRecords", new { patientId = patientId });
            }

            return View(record);
        }

        [RolesAuthorizationFilter(Roles = "Patient")]
        public ActionResult MyRecord()
        {
            var records = _medicalExaminationLogic.GetAllRecordsFromPatientShort(User.Identity.GetUserId());
            var recordsViewModel = AutoMapper.Mapper.Map<IEnumerable<RecordShort>, IEnumerable<RecordListViewModel>>(records);
            return View("AllRecords", recordsViewModel);
        }
    }
}

OnlineMedic.Web/Views/Calendar/MyCalendarDoctor.cshtml
@model OnlineMedic.Web.ViewModels.CalendarEntryViewModel

@{
    ViewBag.Title = "MyCalendarDoctor";
}

<h2>My Calendar</h2>
<hr/>

<div class="container">
    <div class="row">
        <a href="?date=@ViewBag.PrevDate">
            <span class="glyphicon glyphicon-chevron-left"></span>
        </a>        
        <a class="pull-right" href="?date=@ViewBag.NextDate">
            <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th></th>
                @foreach (string dayName in ViewBag.DaysNames)
                {
                    @Html.Raw(HttpUtility.HtmlDecode(dayName));

                }
            </tr>
        </thead>
        <tbody>
            @foreach (List<OnlineMedic.Web.ViewModels.CalendarEntryViewModel> calEntryList in ViewBag.CalendarEntries)
            {
                <tr>
                    <td>@calEntryList[0].Time</td>
                    @foreach (var calEntry in calEntryList)
                    {
                        if (calEntry.Status == "R")
                        {
                            <td>
                                <div class="entry-record alert alert-danger cursor-pointer" data-time="@calEntry.Time" data-status="@calEntry.Status" data-date="@calEntry.Date" data-patient-id="@calEntry.UserId">
                                    @calEntry.Name
                                </div>
                            </td>
                        }
                        else if (calEntry.Status == "P")
                        {
                            <td>
                                <div class="entry-record alert alert-info cursor-pointer" data-time="@calEntry.Time" data-status="@calEntry.Status" data-date="@calEntry.Date" data-patient-id="@calEntry.UserId" >
                                    @calEntry.Name
                                </div>
                            </td>
                        }
                        else if (calEntry.Status == "F")
                        {
                            <td>
                                <div class="entry-record alert alert-success cursor-pointer" data-time="@calEntry.Time" data-status="@calEntry.Status" data-date="@calEntry.Date" >
                                    Free
                                </div>
                            </td>
                        }
                        else if (calEntry.Status == "E")
                        {
                            <td>
                                <div class="entry-record alert alert-warning cursor-pointer" data-time="@calEntry.Time" data-status="@calEntry.Status" data-date="@calEntry.Date">
                                    Empty
                                </div>
                            </td>
                        }
                    }
                </tr>
            }
        </tbody>
    </table>

    <div>
        <button type="button" class="btn btn-success col-md-2 col-md-offset-7">All to Free</button>        
        <button type="button" class="btn btn-warning col-md-2 col-md-offset-1">All To Empty</button>
    </div>
</div>


<!-- Modal Pending -->
<div class="modal fade" id="pendingModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Pending request</h4>
            </div>
            <div class="modal-body">
                <p>Do you want to confirm reservation?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default openPatientModal" data-dismiss="modal">Open Patient</button>
                <button id="rejectPendingModal" type="button" class="btn btn-primary" data-dismiss="modal">Reject</button>
                <button id="confirmPendingModal" type="button" class="btn btn-primary" data-dismiss="modal">Confirm</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

<!-- Modal Reserved -->
<div class="modal fade" id="reservedModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Reservation</h4>
            </div>
            <div class="modal-body">
                <p>Do you want to cancel the reservation?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default openPatientModal" data-dismiss="modal">Open Patient</button>
                <button id="cancelReservedModal" type="button" class="btn btn-primary" data-dismiss="modal">Cancel Entry</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="errorModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Problem with entry</h4>
            </div>
            <div class="modal-body">
                <p>Please refresh the page</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>



@section Scripts {
    <script src="~/Scripts/calendar.signalR.js"></script>
    <script>
        var _doctorId = "@ViewBag.DoctorId";
        $(document).ready(function () {
            var thisVariable = new Object();
            $(".entry-record").click(function () {
                var status = $(this).attr("data-status");
                thisVariable = this;
                if (status == "F") {
                    $.post("@Url.Action("InvertFreeEntry", "Calendar")", { date: $(this).attr("data-date"), time: $(this).attr("data-time") })
                      .done(function (data) {
                          if (data == "ok") {
                              $(thisVariable).html("Empty");
                              $(thisVariable).removeClass("alert-success");
                              $(thisVariable).addClass("alert-warning");
                              $(thisVariable).attr("data-status", "E");
                          }
                          else {
                              $('#errorModal').modal('show');
                          }
                      });
                }
                else if (status == "E") {
                    $.post("@Url.Action("InvertEmptyEntry", "Calendar")", { date: $(this).attr("data-date"), time: $(this).attr("data-time") })
                      .done(function (data) {
                          if (data == "ok") {
                              $(thisVariable).html("Free");
                              $(thisVariable).removeClass("alert-warning");
                              $(thisVariable).addClass("alert-success");
                              $(thisVariable).attr("data-status", "F");
                          }
                      });
                }
                else if (status == "R") {
                    $('#reservedModal').modal('show');
                }
                else if (status == "P") {
                    $('#pendingModal').modal('show');
                }
            });

            $("#rejectPendingModal").click(function () {
                $.post("@Url.Action("RejectEntryDoctor", "Calendar")", { date: $(thisVariable).attr("data-date"), time: $(thisVariable).attr("data-time") })
                      .done(function (data) {
                          if (data == "ok") {
                              $(thisVariable).html("Free");
                              $(thisVariable).removeClass("alert-info");
                              $(thisVariable).addClass("alert-success");
                              $(thisVariable).attr("data-status", "F");
                          }
                          else {
                              $('#errorModal').modal('show');
                          }
                      });
            });

            $("#confirmPendingModal").click(function () {
                $.post("@Url.Action("ConfirmEntryDoctor", "Calendar")", { date: $(thisVariable).attr("data-date"), time: $(thisVariable).attr("data-time") })
                      .done(function (data) {
                          if (data == "ok") {
                              $(thisVariable).removeClass("alert-info");
                              $(thisVariable).addClass("alert-danger");
                              $(thisVariable).attr("data-status", "R");
                          }
                          else {
                              $('#errorModal').modal('show');
                          }
                      });
            });

            $("#cancelReservedModal").click(function () {
                $.post("@Url.Action("CancelReservedDoctor", "Calendar")", { date: $(thisVariable).attr("data-date"), time: $(thisVariable).attr("data-time"), patientId: $(thisVariable).attr("data-patient-id") })
                      .done(function (data) {
                          if (data == "ok") {
                              $(thisVariable).html("Free");
                              $(thisVariable).removeClass("alert-danger");
                              $(thisVariable).addClass("alert-success");
                              $(thisVariable).attr("data-status", "F");
                          }
                          else {
                              $('#errorModal').modal('show');
                          }
                      });
            });

            $(".openPatientModal").click(function () {
                var patientUrl = "@Url.Action("AllRecords", "Patients", new { patientId = "patientId" })";
                patientUrl = patientUrl.replace("patientId", $(thisVariable).attr("data-patient-id"));
                window.open(patientUrl);
            });


        });
    </script>
}

OnlineMedic.Web/Views/Calendar/MyCalendarPatient.cshtml
@{
    ViewBag.Title = "MyCalendarPatient";
}

<h2>My Calendar</h2>

<div class="container">
    <div class="row">
        <a href="?date=@ViewBag.PrevDate">
            <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="pull-right" href="?date=@ViewBag.NextDate">
            <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th></th>
                @foreach (string dayName in ViewBag.DaysNames)
                {
                    @Html.Raw(HttpUtility.HtmlDecode(dayName));

                }
            </tr>
        </thead>
        <tbody>
            @foreach (List<OnlineMedic.Web.ViewModels.CalendarEntryViewModel> calEntryList in ViewBag.CalendarEntries)
            {
                <tr>
                    <td>@calEntryList[0].Time</td>
                    @foreach (var calEntry in calEntryList)
                    {
                        if (calEntry.Status == "E")
                        {
                            <td></td>
                        }
                        else if (calEntry.Status == "F")
                        {
                            <td></td>
                        }
                        else if (calEntry.Status == "M")
                        {
                            <td>
                                <div class="entry-record alert alert-danger cursor-pointer" data-time="@calEntry.Time" data-status="@calEntry.Status" data-date="@calEntry.Date" data-doctor-id="@calEntry.UserId">
                                    @calEntry.Name
                                </div>
                            </td>
                        }
                        else if (calEntry.Status == "P")
                        {
                            <td>
                                <div class="entry-record alert alert-info cursor-pointer" data-time="@calEntry.Time" data-status="@calEntry.Status" data-date="@calEntry.Date" data-doctor-id="@calEntry.UserId">
                                    @calEntry.Name
                                </div>
                            </td>
                        }
                    }
                </tr>
            }
        </tbody>
    </table>
</div>


<!-- Modal Reserved -->
<div class="modal fade" id="reservedModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Reservation</h4>
            </div>
            <div class="modal-body">
                <p>Do you want to cancel the reservation?</p>
            </div>
            <div class="modal-footer">
                <button id="openDoctorModal" type="button" class="btn btn-default" data-dismiss="modal">Open Doctor</button>
                <button id="cancelReservedModal" type="button" class="btn btn-primary" data-dismiss="modal">Cancel Entry</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="errorModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Problem with entry</h4>
            </div>
            <div class="modal-body">
                <p>Please refresh the page</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

@section Scripts {
    <script src="~/Scripts/calendar.signalR.js"></script>
    <script>
        var _patientId = "@ViewBag.PatientId";
        $(document).ready(function () {
            var thisVariable = new Object();
            $(".entry-record").click(function () {
                var status = $(this).attr("data-status");
                thisVariable = this;

                if (status == "M" || status == "P") {
                    $('#reservedModal').modal('show');
                }
            });


            $("#cancelReservedModal").click(function () {
                $.post("@Url.Action("CancelReservedPatient", "Calendar")", { date: $(thisVariable).attr("data-date"), time: $(thisVariable).attr("data-time"), doctorId: $(thisVariable).attr("data-doctor-id") })
                      .done(function (data) {
                          if (data == "ok") {
                              $(thisVariable).html("");
                              $(thisVariable).removeClass("alert-danger");
                              $(thisVariable).removeClass("alert-info");
                              $(thisVariable).attr("data-status", "E");
                          }
                          else {
                              $('#errorModal').modal('show');
                          }
                      });
            });

            $("#openDoctorModal").click(function () {
                var patientUrl = "@Url.Action("Details", "Doctors", new { id = "doctorId" })";
                patientUrl = patientUrl.replace("doctorId", $(thisVariable).attr("data-doctor-id"));
                window.open(patientUrl);
            });

        });
    </script>
}